// File generated by FlutterFire CLI for project: foodiego-f2abf (FoodieGo)
// https://firebase.google.com/docs/flutter/setup

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  /// Real keys from flutterfire configure — project foodiego-f2abf.
  static const bool isConfigured = true;

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-F_wd8p3VSJzSgwtVFVmw9lRYg2gFDbo',
    appId: '1:516975026304:web:965307f679df993b228665',
    messagingSenderId: '516975026304',
    projectId: 'foodiego-f2abf',
    authDomain: 'foodiego-f2abf.firebaseapp.com',
    storageBucket: 'foodiego-f2abf.firebasestorage.app',
    measurementId: 'G-MZV2FN664L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWAhGomPoZjHcJVw5aZS2MxxEE4Z6Q1z8',
    appId: '1:516975026304:android:e09979db1486163a228665',
    messagingSenderId: '516975026304',
    projectId: 'foodiego-f2abf',
    storageBucket: 'foodiego-f2abf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAp1U779ND1LM-j47hTrFfzYuCteLp3W0A',
    appId: '1:516975026304:ios:e97b07505b5072c4228665',
    messagingSenderId: '516975026304',
    projectId: 'foodiego-f2abf',
    storageBucket: 'foodiego-f2abf.firebasestorage.app',
    iosBundleId: 'com.example.foodOrderApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAp1U779ND1LM-j47hTrFfzYuCteLp3W0A',
    appId: '1:516975026304:ios:e97b07505b5072c4228665',
    messagingSenderId: '516975026304',
    projectId: 'foodiego-f2abf',
    storageBucket: 'foodiego-f2abf.firebasestorage.app',
    iosBundleId: 'com.example.foodOrderApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-F_wd8p3VSJzSgwtVFVmw9lRYg2gFDbo',
    appId: '1:516975026304:web:d03b5dfd2ce299bb228665',
    messagingSenderId: '516975026304',
    projectId: 'foodiego-f2abf',
    authDomain: 'foodiego-f2abf.firebaseapp.com',
    storageBucket: 'foodiego-f2abf.firebasestorage.app',
    measurementId: 'G-XMGQ7T0QF2',
  );
}
